source 'https://rubygems.org'

gem "unicorn-rails"
gem 'jquery-rails'
gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'sqlite3'
gem 'uglifier', '>= 1.3.0'

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem "brakeman"
  gem "guard-rspec"
  gem "pry-debugger"
  gem "rspec-rails"
  gem "rubocop"
end
