source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'

group :doc do
  gem 'sdoc', require: false
end

gem "unicorn-rails"
group :development, :test do
  gem "brakeman"
  gem "guard-rspec"
  gem "pry-debugger"
  gem "rspec-rails"
  gem "rubocop"
end
